name: Linux Build

on: [ push ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: sudo apt update && sudo apt install ninja-build lld-8 libx11-dev xorg-dev libglu1-mesa-dev

      - name: Download UltralightCore
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.ACCESS_TOKEN}}
          workflow: linux.yml
          workflow_conclusion: success
          name: ultralight-core
          path: deps/UltralightCore
          repo: InsigniaRSPS/UltralightCore-src

      - name: Download WebKitLibraries
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.ACCESS_TOKEN}}
          workflow: linux.yml
          workflow_conclusion: success
          name: webkitlibraries
          path: deps/WebKitLibraries
          repo: InsigniaRSPS/WebCore-deps

      - name: Download WebCore
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.ACCESS_TOKEN}}
          workflow: linux.yml
          workflow_conclusion: success
          name: webcore
          path: deps/WebCore
          repo: InsigniaRSPS/WebCore

      - name: Download Ultralight
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.ACCESS_TOKEN}}
          workflow: linux.yml
          workflow_conclusion: success
          name: ultralight
          path: deps/Ultralight
          repo: InsigniaRSPS/Ultralight-src

      - name: Build AppCore
        run: chmod 777 ./make && ./make

      - name: Check if build exists
        run: (test -d "build/out") || exit 1

      - uses: actions/upload-artifact@v2
        with:
          name: appcore
          path: build/out/