name: Windows Build

on: [ push ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - run: choco install ninja gperf

      - name: Download UltralightCore
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.ACCESS_TOKEN}}
          workflow: windows.yml
          workflow_conclusion: success
          name: ultralight-core
          path: deps/UltralightCore
          repo: InsigniaRSPS/UltralightCore-src

      - name: Download WebCore
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.ACCESS_TOKEN}}
          workflow: windows.yml
          workflow_conclusion: success
          name: webcore
          path: deps/WebCore
          repo: InsigniaRSPS/WebCore

      - name: Download Ultralight
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.ACCESS_TOKEN}}
          workflow: windows.yml
          workflow_conclusion: success
          name: ultralight
          path: deps/Ultralight
          repo: InsigniaRSPS/Ultralight-src

      - name: Build AppCore
        run: ./make release x64 local static static_crt

      - uses: actions/upload-artifact@v2
        with:
          name: appcore
          path: build_release_x64_static_MT/out/